= Teach spreadsheets
:gitHubUserName: oliviercailloux
:groupId: io.github.{gitHubUserName}
:artifactId: teach_spreadsheets
:repository: Teach-spreadsheets

image:https://github.com/{gitHubUserName}/{repository}/workflows/Maven%20CI/badge.svg["Build Status", link="https://github.com/{gitHubUserName}/{repository}/actions"]

A Java project developed by students during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in https://dauphine.psl.eu/formations/licences/informatique-des-organisations/l3-methodes-informatiques-appliquees-pour-la-gestion-des-entreprises[L3 MIAGE Alternance]).

The code is hereby published under the MIT License, with the permission of the contributors.

The project documentation is link:Doc/README.adoc[here].


== Plan Itération 2 UML 

Project members : Mohamed I, Mohamed A, Mehdi, Ryan, Nael, Samba, Elena

'''

*SMPO : Nael*

'''


*Team 1 : Samba & Mehdi*

* Implementation of the proposed changes and improvements of the class diagrams: https://github.com/oliviercailloux-org/dep-git-Teach_spreadsheets/blob/f1f999ee8368e8950394f53e16ba524e8219d248/Doc/Images/Class_Ods_Write_Office365_Upload.png["Class_Ods_Write_Office365_Upload"] and https://github.com/oliviercailloux-org/dep-git-Teach_spreadsheets/blob/f1f999ee8368e8950394f53e16ba524e8219d248/Doc/Images/Class_Ods_Write_Office365_Cloud.png["Class_Ods_Write_Office365_Cloud"] started on the branch https://github.com/oliviercailloux-org/dep-git-Teach_spreadsheets/tree/dev_Ryan_ElMahdi[dev_Ryan_ElMahdi] (Voir PR #3) So the new branch will be created from this branch https://github.com/oliviercailloux-org/dep-git-Teach_spreadsheets/tree/dev_Ryan_ElMahdi[dev_Ryan_ElMahdi] and have to be named : Creation_spreadsheet_online-it2

* Update of README : Presentation , content  and  recover the existing readme that has been overwritten at iteration number one

* Continue research and testing in order to find a solution allowing the connection to Microsoft 365 and the creation of an Excel file and writing in this same file ( the https://github.com/oliviercailloux-org/dep-git-Teach_spreadsheets/blob/84afed94d42b61258a8e9819fc65781796ec903e/Doc/Doc_Excel_Api.adoc[Tutorial to create a sheet online] on the branch https://github.com/oliviercailloux-org/dep-git-Teach_spreadsheets/tree/dev_samba_nael[dev_samba_nael] can possibly be reused) 

'''
*Team 2 : Mohammed A & Elena*

* Implementation of the proposed changes and improvement of the class diagrams started on the branch dev_Mohamed_x2 (https://github.com/oliviercailloux-org/dep-git-Teach_spreadsheets/blob/32141a63acb93246a15d8be48ce75bcdd8314ab7/Doc/Images/Base%20classes%20modified.png[Modification of class diagrams "Base classes"]) for the task : "the application displays the difference between the total of hours desired and the total of hours assigned. The total of hours assigned are gathered for every teacher for every cell where he appears” (Voir PR #2). So the new branch will be created from this branch https://github.com/oliviercailloux-org/dep-git-Teach_spreadsheets/tree/dev_Mohamed_x2 and have to be named : Difference_hoursDesired_hoursAssigned-it2

* Sequence diagram  as proposed by Mr Cailloux (At PR #2 's review)

* Update of README : Presentation , content  and  recover the existing readme that has been overwritten at iteration number one

'''
*Team 3 : Ryan & Mohammed I*

* Sequence diagram and class diagram for the task : “If a 365 sheet already exists, the application overwrites the information in the displayed cells; and indicates a new tab the changes made”. The branch will be created from the branch master and named Sheet_already_exists-it2


== Plan Itération 3 UML 

'''

*SMPO : Ryan Hamiche*

'''

*Team 1 : Mehdi & Mohamed A*

* Bien se renseigner sur le package write, à propos de la création et la manière dont on écrit dans la feuille de calcul (existant)

* S’en inspirer pour créer un diagramme de classe concernant l’écriture de feuilles de calcul en ligne en prenant bien compte des commentaires de la PR#7. Il contiendra deux classes au moins (ou plus), une sur la modification de feuilles en ligne (générale et utilisable dans n’importe quel projet), et une autre classe qui utilise la première et fasse le lien à nos besoins. Créer une documentation sur comment cela va impacter le projet et comment on pourra adapter aisément l’ancien projet au notre. 


'''
*Team 2 : Samba & Nael*

* Améliorer le tutoriel sur les modifications de feuille de calcul Office365. Implémentation de classes et méthodes pour modifier cellule (précisée en entrée) et mise en page de cette cellule dans un package dédié. Faire des tests pour vérifier si cela convient à nos besoins (surtout sur la modification de feuille de calcul)

* Création application officielle Azure Directory pour le projet avec compte Outlook dédié pour que tout le monde puisse y accéder.


'''
*Team 3 : Elena & Mohamed I*

* Peaufiner et finaliser la tâche : L’application affiche la différence entre le nombre d’heures total désiré et le total affecté, pour chaque enseignant, dans chaque cellule où il apparait, par exemple : "[− 30h]" . En prenant en compte les commentaires et indications de la PR#8

* Proposer une documentation pour la tâche :  Si une feuille 365 existe déjà, l’application écrase les informations dans les cellules correspondantes ; et indique dans un nouvel onglet les modifications apportées. Cette documentation décrira la lecture, les calculs/vérifications de modifications (à la main) de la feuille de calcul et le renseignement de modifications apportées dans un nouvel onglet.

* Préparer un plan pour la présentation finale. 

== Plan Itération 1 JAVA

'''

*SMPO : Mohamed Irazzi*

'''

*Team 1 : Mehdi & Nael*

* Implémenter le package d’authentification et la classe WriterLib (se trouvant dans le package Write se trouvant lui même dans le package Online).

* S’informer sur Jarris et essayer de l’implémenter.


'''
*Team 2 : Samba & Mohamed A*

* Faire le Caneva du fichier qui va être en sortie en ligne -> affectation service 20/21 (Alimenter la colonne "type de cours").


'''
*Team 3 : Elena & Ryan*

* Commencer à implémenter la classe AssignmentPerTeacher (se trouvant dans le package Write se trouvant lui même dans le package Online).

== Plan Itération 4 UML

'''

*SMPO : Elena*

'''

*Team 1 : Mohamed I et Ryan*

* Pour la tâche "Si une feuille 365 existe déjà, l’application écrase les informations dans les cellules correspondantes ; et indique dans un nouvel onglet les modifications apportées", faire une documentation détaillée dessus (quel types d'erreurs vont être repérées et corrigées et comment). Nous n'allons pas écraser la feuille déjà existante, mais allons en créer une nouvelle avec les modifications et signaler les erreurs détectées. Suite à cela, nous allons faire un diagramme de séquence pour illuster.



'''
*Team 2 : Mohamed A & Samba*

* Travailler sur la nouvelle version de l'authentification (https://docs.microsoft.com/en-us/graph/tutorials/java?tutorial-step=1) et faire un exemple de code permettant de s'authentifier avec cette nouvelle version. Mettre à jour si possible (et/ou nécessaire) le tutoriel.


'''
*Team 3 : Mehdi & Nael*

* Travailler sur la documentation UML de l'écriture en ligne ; focus sur le XlsSummarizer (programmer à l'itération 1 de java sur la PR#16 https://github.com/oliviercailloux-org/dep-git-Teach_spreadsheets/pull/16 )  + prise en considération remarque PR #13 https://github.com/oliviercailloux-org/dep-git-Teach_spreadsheets/pull/13 tout en conservant pour le moment l'authentification actuelle (qui sera actualisée par la suite, comme discuté en réunion avec M. Cailloux)



== Plan Itération 2 JAVA

'''

*SMPO : Ibouda El Mahdi*

'''

*Team 1 : Moha I & Ryan*

* Chercher et implémenter une solution qui permettrait au programme de se connecter directement à Internet et de s'authentifier automatiquement, ce qui permettra également d'automatiser les tests.

* Création d'une interface générale et deux implémentations, dont une locale.


'''
*Team 2 : Samba & Nael*

* Implémenter la nouvelle méthode d'authentification et la nouvelle manière d'écrire en ligne (càd mettre à jour la classe WorkSheetWriter).


'''
*Team 3 : Moha A & Elena*

* Comme expliqué à la link:https://github.com/oliviercailloux-org/dep-git-Teach_spreadsheets/pull/16[PR #16], la modification du style ou de la police d'une cellule ne fonctionne pas, en effet lorsque l'on souhaite modifier le style d'une cellule, ce sont toutes les cellules qui sont modifiées. Nous allons donc retravailler sur ça en partant de la nouvelle version de Microsoft 365 qui va être implémentée.

* Si l'utilisation de la nouvelle version de Microsoft 365 ne résout pas le problème, nous allons donc partir sur l'implémentation des classes du package Read.


== Plan Itération UML itération 5

'''

*SMPO : ALASSAF Mohamed*

'''

*Team 1 : Nael TALBI & Mohamed IRAZZI*

* Faire le diagramme de classe du package "bimodal" qui contient une interface avec une méthode d'écriture. Celle-ci doit permettre à la fois (selon les paramètres -> URL) d'écrire en ligne ou en local



'''
*Team 2 : Samba DIOUF & El Mahdi IBOUDA*

* Suite de la PR (https://github.com/MohamedALASSAF/Teach-spreadsheets-authentification/pull/1), retravailler la documentation sur la nouvelle facon de s'authentifier en prenant en compte les remarques du professeur en l'ajoutant au tutoriel général (https://github.com/oliviercailloux-org/dep-git-Teach_spreadsheets/blob/Creation_spreadsheet_online-it3/Doc/Excel_Online_Api_Tutorial.adoc)


'''
*Team 3 : Ryan HAMICHE & Elena SOCOLOVA *

*  Suite aux remarques et à la suggestion faitent à la PR #29, faire une documentation/tutoriel avec potentiellement un diagramme de séquence pour la lecture d'une feuille excel en ligne en téléchargeant en local la feuille Excel en ligne, et utilisant l’approche existante de l’année passée pour lire la feuille.

== Plan Itération 3 JAVA

'''

*SMPO : Irazzi Mohamed*

'''

*Team 1 : Nael et Mehdi *

* Suite à la [PR](https://github.com/oliviercailloux-org/dep-git-Teach_spreadsheets/pull/33), faire l'implémentation de l'interface WorksheetWriter composé des deux classes : OnlineWorksheetWriter et LocalWorksheetWriter.


'''
*Team 2 : Samba & Mohamed Alassaf*

* Implémenter la nouvelle méthode d'authentification et la nouvelle manière d'écrire en ligne (càd mettre à jour la classe WorkSheetWriter).


'''
*Team 3 : Ryan A & Elena*

* 

* Si l'utilisation de la nouvelle version de Microsoft 365 ne résout pas le problème, nous allons donc partir sur l'implémentation des classes du package Read.



== Credits
The Icons used in the gui are made by link:https://www.flaticon.com/authors/freepik[Freepik], link:https://www.flaticon.com/authors/xnimrodx[nimrodx] and link:https://www.flaticon.com/authors/prosymbols[Prosymbols] from link:https://www.flaticon.com/[www.flaticon.com].
