= Teach spreadsheets
:gitHubUserName: oliviercailloux
:groupId: io.github.{gitHubUserName}
:artifactId: teach_spreadsheets
:repository: Teach-spreadsheets

image:https://github.com/{gitHubUserName}/{repository}/workflows/Maven%20CI/badge.svg["Build Status", link="https://github.com/{gitHubUserName}/{repository}/actions"]

A Java project developed by students during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in https://dauphine.psl.eu/formations/licences/informatique-des-organisations/l3-methodes-informatiques-appliquees-pour-la-gestion-des-entreprises[L3 MIAGE Alternance]).

The code is hereby published under the MIT License, with the permission of the contributors.

The project documentation is link:Doc/README.adoc[here].

== Logos' Credits
The Icons used in the gui are made by link:https://www.flaticon.com/authors/freepik[Freepik], link:https://www.flaticon.com/authors/xnimrodx[nimrodx] and link:https://www.flaticon.com/authors/prosymbols[Prosymbols] from link:https://www.flaticon.com/[www.flaticon.com].

== Global idea of the project 
The main functionalities that this project will implement are described in the link:Doc\README.adoc#UseCaseDiag[use case diagram]. +
You can see how our program's gui looks like in link:Doc\README.adoc#GuiDescription[gui description]. +
The way we imagine the process of assignment is described in the link:Doc\README.adoc#SeqDiag[sequence diagram]. +
The packages in our program are modelled in the link:Doc\README.adoc#Package[package diagram]. +
The classes implemented are described in the link:Doc\README.adoc#ClassDiag[class diagram].


